In [58]:
import torch

x = torch.rand(2, 2)
print(x.dtype)
x

torch.float32


tensor([[0.4903, 0.6568],
        [0.0160, 0.4430]])

In [59]:
y = torch.rand([2, 2])
y

tensor([[0.7458, 0.7727],
        [0.9552, 0.0730]])

In [60]:
z = x + y
z

tensor([[1.2360, 1.4295],
        [0.9712, 0.5160]])

In [61]:
y.add_(x) # in pytorch, every method with _, means that it is an in-place operation that will modify the .notated vriable
y

tensor([[1.2360, 1.4295],
        [0.9712, 0.5160]])

In [62]:
x * y

tensor([[0.6060, 0.9388],
        [0.0156, 0.2286]])

In [63]:
torch.mul(x,y)

tensor([[0.6060, 0.9388],
        [0.0156, 0.2286]])

In [64]:
x = torch.rand(4,4)
x

tensor([[0.8613, 0.1291, 0.4818, 0.0622],
        [0.5601, 0.3078, 0.9207, 0.5163],
        [0.1165, 0.2745, 0.8226, 0.7793],
        [0.3795, 0.0444, 0.1744, 0.4872]])

In [77]:
y = x.view(16) # unpacks x into one dimention
y

tensor([0.8613, 0.1291, 0.4818, 0.0622, 0.5601, 0.3078, 0.9207, 0.5163, 0.1165,
        0.2745, 0.8226, 0.7793, 0.3795, 0.0444, 0.1744, 0.4872])

In [80]:
y = x.view(-1, 8) # unpacks x into one dimention - resizing tensors
y

tensor([[0.8613, 0.1291, 0.4818, 0.0622, 0.5601, 0.3078, 0.9207, 0.5163],
        [0.1165, 0.2745, 0.8226, 0.7793, 0.3795, 0.0444, 0.1744, 0.4872]])

In [81]:
import numpy as np

a = torch.ones(5) # converting from tensor to numpy array
a

tensor([1., 1., 1., 1., 1.])

In [82]:
b = a.numpy() 
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [85]:
a = np.ones(5) # converting from numpy array to tensor
a

array([1., 1., 1., 1., 1.])

In [87]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [88]:
torch.manual_seed(1729)
t1 = torch.rand(2,2)
t1

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

In [89]:
t2 = torch.rand(2,2)
t2

tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

In [90]:
torch.manual_seed(1729)
t3 = torch.rand(2,2)
t3

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

In [96]:
torch.rand(2,2) - 0.5 * 2

tensor([[-0.4938, -0.1531],
        [-0.7412, -0.7293]])

In [120]:
# first model attempt
torch.manual_seed(1729)
x = torch.randn(1,10)
prev_h = torch.rand(1,20)
W_h = torch.rand(20,20)
W_x = torch.randn(20,10)

i2h = torch.mm(W_x, x.t())
h2h = torch.mm(W_h, prev_h.t())

next_h = h2h + i2h
next_h = next_h.tanh()

loss = next_h.sum()
loss

tensor(17.7615)

In [121]:
#loss.backward()

In [125]:
shape = (2,3)
rand_tensor = torch.rand(shape)
rand_tensor

rand2_tensor = torch.rand(rand_tensor.shape)
rand2_tensor


tensor([[0.0925, 0.9457, 0.7591],
        [0.4223, 0.2485, 0.0501]])